input_stream_name = 'shared_services_input_prod'
input_stream_region = 'eu-west-2'
error_stream_name = 'message_error_prod'
error_stream_region = 'eu-west-2'
upload_url = 's3://uk.ac.jisc.alpha.researchdata.s3.uoj.autoupload'
